export SALT_SSH_DOCKER_IMAGE="${SALT_SSH_DOCKER_IMAGE:-salt-ssh}"
# 3006.5 - working pygit states/pillars
export SALT_SSH_DOCKER_TAG="${SALT_SSH_DOCKER_TAG:-3006.5}"
declare -A SALT_SSH_DOCKER_BUILD_ARGS
SALT_SSH_DOCKER_BUILD_ARGS['OS_VERSION']="9-slim"
SALT_SSH_DOCKER_BUILD_ARGS['PYGIT2_VERSION']="1.14.1"
SALT_SSH_DOCKER_BUILD_ARGS['IMAGE_AUTHOR']="lightvik@yandex.ru"
SALT_SSH_DOCKER_BUILD_ARGS['ARCH']="x86_64"
SALT_SSH_DOCKER_BUILD_ARGS['SALTSTACK_VERSION']="${SALT_SSH_DOCKER_TAG}"
export SALT_SSH_DOCKER_BUILD_ARGS
declare -A SALT_SSH_CONTAINER_ENVIRONMENT
SALT_SSH_CONTAINER_ENVIRONMENT['GIT_USER']="user"
SALT_SSH_CONTAINER_ENVIRONMENT['GIT_PASSWORD']="password"
export SALT_SSH_CONTAINER_ENVIRONMENT
declare -a SALT_SSH_ARGS
# SALT_SSH_ARGS+=('')
export SALT_SSH_ARGS
